input_folder: "src/data/raw"
output_folder: "src/data/ready"
output_file: "clean.xlsx"
mapeamento:
  Código: "Código"
  Descrição: "Descrição"
  Un: "Unidade"
  NCM: "NCM"
  Origem: "Origem"
  Preço: "Preço"
  IPI fixo: "Valor IPI fixo"
  Obs: "Observações"
  Situação: "Situação"
  Estoque: "Estoque"
  Preço de custo: "Preço de custo"
  Cód Fornecedor: "Cód. no fornecedor"
  Fornecedor: "Fornecedor"
  Localização: "Localização"
  Estoque Máximo: "Estoque máximo"
  Estoque Mínimo: "Estoque mínimo"
  Peso líquido: "Peso líquido (Kg)"
  Peso bruto: "Peso bruto (Kg)"
  GTIN: "GTIN/EAN"
  GTIN Embalagem: "GTIN/EAN da Embalagem"
  Descrição Complementar: "Descrição Curta"
  CEST: "CEST"
  Largura embalagem: "Largura do produto"
  Altura embalagem: "Altura do Produto"
  Comprimento embalagem: "Profundidade do produto"
  URL imagem 1: "URL Imagens Externas"
  Categoria: "Categoria do produto"
  Código do produto pai: "Código Pai"
  Unidade por caixa: "Itens p/ caixa"
  Marca: "Marca"
colunas_finais:
  - "ID"
  - "Código"
  - "Descrição"
  - "Un"
  - "NCM"
  - "Origem"
  - "Preço"
  - "IPI fixo"
  - "Obs"
  - "Situação"
  - "Estoque"
  - "Preço de custo"
  - "Cód Fornecedor"
  - "Fornecedor"
  - "Localização"
  - "Estoque Máximo"
  - "Estoque Mínimo"
  - "Peso líquido"
  - "Peso bruto"
  - "GTIN"
  - "GTIN Embalagem"
  - "Descrição Complementar"
  - "CEST"
  - "Código de Enquadramento IPI"
  - "Formato embalagem"
  - "Largura embalagem"
  - "Altura embalagem"
  - "Comprimento embalagem"
  - "Diâmetro embalagem"
  - "Tipo do produto"
  - "URL imagem 1"
  - "URL imagem 2"
  - "URL imagem 3"
  - "URL imagem 4"
  - "URL imagem 5"
  - "URL imagem 6"
  - "Categoria"
  - "Código do produto pai"
  - "Variações"
  - "Marca"
  - "Garantia"
  - "Sob encomenda"
  - "Preço promocional"
  - "Imagem externa 1"
  - "Imagem externa 2"
  - "Imagem externa 3"
  - "Imagem externa 4"
  - "Imagem externa 5"
  - "Imagem externa 6"
  - "Link do vídeo"
  - "Título SEO"
  - "Descrição SEO"
  - "Palavras chave SEO"
  - "Slug"
  - "Dias para preparação"
  - "Controlar lotes"
  - "Unidade por caixa"
  - "Imagem externa 7"
  - "Imagem externa 8"
  - "Imagem externa 9"
  - "Imagem externa 10"
  - "Markup"
  - "Permitir inclusão nas vendas"
  - "EX TIPI"
